# Generated by Django 3.1.6 on 2021-02-25 10:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 2, 25, 10, 37, 45, 147604, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 2, 25, 10, 37, 45, 148629, tzinfo=utc))),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello_app.tasklist')),
            ],
        ),
    ]
