# Generated by Django 3.1.6 on 2021-02-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0002_auto_20210225_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('IP', 'In Progress'), ('D', 'Dropped')], default=('IP', 'In Progress'), max_length=2),
        ),
    ]
